-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (..)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Api.Scalar.Id


type alias Json =
    Api.Scalar.Json


type alias Timestamptz =
    Api.Scalar.Timestamptz


type alias Uuid =
    Api.Scalar.Uuid


codecs : Api.Scalar.Codecs Id Json Timestamptz Uuid
codecs =
    Api.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecJson = defaultCodecs.codecJson
        , codecTimestamptz = defaultCodecs.codecTimestamptz
        , codecUuid = defaultCodecs.codecUuid
        }
