-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Articles_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "articles"

  - Articles\_pkey - unique or primary key constraint

-}
type Articles_constraint
    = Articles_pkey


list : List Articles_constraint
list =
    [ Articles_pkey ]


decoder : Decoder Articles_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "articles_pkey" ->
                        Decode.succeed Articles_pkey

                    _ ->
                        Decode.fail ("Invalid Articles_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Articles_constraint -> String
toString enum =
    case enum of
        Articles_pkey ->
            "articles_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Articles_constraint
fromString enumString =
    case enumString of
        "articles_pkey" ->
            Just Articles_pkey

        _ ->
            Nothing
