-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Comments_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "comments"

  - Comments\_pkey - unique or primary key constraint

-}
type Comments_constraint
    = Comments_pkey


list : List Comments_constraint
list =
    [ Comments_pkey ]


decoder : Decoder Comments_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "comments_pkey" ->
                        Decode.succeed Comments_pkey

                    _ ->
                        Decode.fail ("Invalid Comments_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Comments_constraint -> String
toString enum =
    case enum of
        Comments_pkey ->
            "comments_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Comments_constraint
fromString enumString =
    case enumString of
        "comments_pkey" ->
            Just Comments_pkey

        _ ->
            Nothing
