-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Likes_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "likes"

  - Article\_id - column name
  - User\_id - column name

-}
type Likes_select_column
    = Article_id
    | User_id


list : List Likes_select_column
list =
    [ Article_id, User_id ]


decoder : Decoder Likes_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "article_id" ->
                        Decode.succeed Article_id

                    "user_id" ->
                        Decode.succeed User_id

                    _ ->
                        Decode.fail ("Invalid Likes_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Likes_select_column -> String
toString enum =
    case enum of
        Article_id ->
            "article_id"

        User_id ->
            "user_id"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Likes_select_column
fromString enumString =
    case enumString of
        "article_id" ->
            Just Article_id

        "user_id" ->
            Just User_id

        _ ->
            Nothing
