-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Users_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "users"

  - Email - column name
  - Username - column name

-}
type Users_select_column
    = Email
    | Username


list : List Users_select_column
list =
    [ Email, Username ]


decoder : Decoder Users_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "email" ->
                        Decode.succeed Email

                    "username" ->
                        Decode.succeed Username

                    _ ->
                        Decode.fail ("Invalid Users_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Users_select_column -> String
toString enum =
    case enum of
        Email ->
            "email"

        Username ->
            "username"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Users_select_column
fromString enumString =
    case enumString of
        "email" ->
            Just Email

        "username" ->
            Just Username

        _ ->
            Nothing
