-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object.Articles exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hasura.InputObject
import Hasura.Interface
import Hasura.Object
import Hasura.Scalar
import Hasura.ScalarCodecs
import Hasura.Union
import Json.Decode as Decode


about : SelectionSet String Hasura.Object.Articles
about =
    Object.selectionForField "String" "about" [] Decode.string


{-| An object relationship
-}
author : SelectionSet decodesTo Hasura.Object.Users -> SelectionSet decodesTo Hasura.Object.Articles
author object_ =
    Object.selectionForCompositeField "author" [] object_ identity


content : SelectionSet String Hasura.Object.Articles
content =
    Object.selectionForField "String" "content" [] Decode.string


created_at : SelectionSet Hasura.ScalarCodecs.Timestamptz Hasura.Object.Articles
created_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "created_at" [] (Hasura.ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


title : SelectionSet String Hasura.Object.Articles
title =
    Object.selectionForField "String" "title" [] Decode.string
