-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object.Articles_max_fields exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hasura.InputObject
import Hasura.Interface
import Hasura.Object
import Hasura.Scalar
import Hasura.ScalarCodecs
import Hasura.Union
import Json.Decode as Decode


about : SelectionSet (Maybe String) Hasura.Object.Articles_max_fields
about =
    Object.selectionForField "(Maybe String)" "about" [] (Decode.string |> Decode.nullable)


content : SelectionSet (Maybe String) Hasura.Object.Articles_max_fields
content =
    Object.selectionForField "(Maybe String)" "content" [] (Decode.string |> Decode.nullable)


created_at : SelectionSet (Maybe Hasura.ScalarCodecs.Timestamptz) Hasura.Object.Articles_max_fields
created_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "created_at" [] (Hasura.ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


id : SelectionSet (Maybe Int) Hasura.Object.Articles_max_fields
id =
    Object.selectionForField "(Maybe Int)" "id" [] (Decode.int |> Decode.nullable)


title : SelectionSet (Maybe String) Hasura.Object.Articles_max_fields
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)
