-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object.TokenResponse exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hasura.InputObject
import Hasura.Interface
import Hasura.Object
import Hasura.Scalar
import Hasura.ScalarCodecs
import Hasura.Union
import Json.Decode as Decode


email : SelectionSet String Hasura.Object.TokenResponse
email =
    Object.selectionForField "String" "email" [] Decode.string


token : SelectionSet String Hasura.Object.TokenResponse
token =
    Object.selectionForField "String" "token" [] Decode.string


username : SelectionSet String Hasura.Object.TokenResponse
username =
    Object.selectionForField "String" "username" [] Decode.string
