-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object.UnlikeResponse exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hasura.InputObject
import Hasura.Interface
import Hasura.Object
import Hasura.Scalar
import Hasura.ScalarCodecs
import Hasura.Union
import Json.Decode as Decode


article : SelectionSet decodesTo Hasura.Object.Articles -> SelectionSet (Maybe decodesTo) Hasura.Object.UnlikeResponse
article object_ =
    Object.selectionForCompositeField "article" [] object_ (identity >> Decode.nullable)


article_id : SelectionSet (Maybe Int) Hasura.Object.UnlikeResponse
article_id =
    Object.selectionForField "(Maybe Int)" "article_id" [] (Decode.int |> Decode.nullable)
