-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object.UserProfile exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hasura.InputObject
import Hasura.Interface
import Hasura.Object
import Hasura.Scalar
import Hasura.ScalarCodecs
import Hasura.Union
import Json.Decode as Decode


bio : SelectionSet (Maybe String) Hasura.Object.UserProfile
bio =
    Object.selectionForField "(Maybe String)" "bio" [] (Decode.string |> Decode.nullable)


email : SelectionSet String Hasura.Object.UserProfile
email =
    Object.selectionForField "String" "email" [] Decode.string


follows : SelectionSet (List Int) Hasura.Object.UserProfile
follows =
    Object.selectionForField "(List Int)" "follows" [] (Decode.int |> Decode.list)


profile_image : SelectionSet (Maybe String) Hasura.Object.UserProfile
profile_image =
    Object.selectionForField "(Maybe String)" "profile_image" [] (Decode.string |> Decode.nullable)


user_id : SelectionSet Int Hasura.Object.UserProfile
user_id =
    Object.selectionForField "Int" "user_id" [] Decode.int


username : SelectionSet String Hasura.Object.UserProfile
username =
    Object.selectionForField "String" "username" [] Decode.string
