-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object exposing (..)


type Articles
    = Articles


type Articles_mutation_response
    = Articles_mutation_response


type Comments
    = Comments


type Comments_mutation_response
    = Comments_mutation_response


type Follows
    = Follows


type Follows_mutation_response
    = Follows_mutation_response


type Likes
    = Likes


type Likes_aggregate
    = Likes_aggregate


type Likes_aggregate_fields
    = Likes_aggregate_fields


type Likes_avg_fields
    = Likes_avg_fields


type Likes_max_fields
    = Likes_max_fields


type Likes_min_fields
    = Likes_min_fields


type Likes_mutation_response
    = Likes_mutation_response


type Likes_stddev_fields
    = Likes_stddev_fields


type Likes_stddev_pop_fields
    = Likes_stddev_pop_fields


type Likes_stddev_samp_fields
    = Likes_stddev_samp_fields


type Likes_sum_fields
    = Likes_sum_fields


type Likes_var_pop_fields
    = Likes_var_pop_fields


type Likes_var_samp_fields
    = Likes_var_samp_fields


type Likes_variance_fields
    = Likes_variance_fields


type Tags
    = Tags


type Tags_mutation_response
    = Tags_mutation_response


type TokenResponse
    = TokenResponse


type UnlikeResponse
    = UnlikeResponse


type Users
    = Users
