-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object exposing (..)


type Articles
    = Articles


type Articles_mutation_response
    = Articles_mutation_response


type Token
    = Token


type Users
    = Users
