-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object exposing (..)


type Articles
    = Articles


type Articles_mutation_response
    = Articles_mutation_response


type Tags
    = Tags


type Tags_mutation_response
    = Tags_mutation_response


type TokenResponse
    = TokenResponse


type User_profile
    = User_profile


type Users
    = Users
