-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.ScalarCodecs exposing (..)

import Hasura.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Hasura.Scalar.Id


type alias Json =
    Hasura.Scalar.Json


type alias Timestamptz =
    Hasura.Scalar.Timestamptz


type alias Uuid =
    Hasura.Scalar.Uuid


codecs : Hasura.Scalar.Codecs Id Json Timestamptz Uuid
codecs =
    Hasura.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecJson = defaultCodecs.codecJson
        , codecTimestamptz = defaultCodecs.codecTimestamptz
        , codecUuid = defaultCodecs.codecUuid
        }
