service: actions

provider:
  name: aws
  runtime: java8
  region: eu-west-1

package:
  artifact: build/libs/kotlin-serverless-functions-1.0-SNAPSHOT-all.jar

functions:
  server:
    handler: org.http4k.serverless.lambda.LambdaFunction::handle
    environment:
      HTTP4K_BOOTSTRAP_CLASS: Application
    events:
      - http:
          path: /{proxy+}
          method: ANY
