service: actions

provider:
  name: aws
  runtime: java8
  region: eu-west-1

package:
  artifact: build/libs/actions-serrver-1.0.0-all.jar

functions:
  server:
    handler: org.http4k.serverless.lambda.LambdaFunction::handle
    environment:
      HTTP4K_BOOTSTRAP_CLASS: org.realworld.actions.Application
    events:
      - http:
          path: /{proxy+}
          method: ANY
