name: Build

on:
  push:
    branches:
      - foo

jobs:
  push-containers:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v1
      - run: heroku container:login
      - run: heroku container:push -app realworld-hasura web
        working-directory: ./backend/hasura
      - run: heroku container:push -app realworld-actions web
        working-directory: ./backend/actions
