name: CD

on:
  push:
    branches:
      - main

jobs:
  migrate-hasura:
    runs-on: ubuntu-latest
    env:
      HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
      HASURA_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
      HASURA_WORKDIR: ./backend/hasura
    steps:
      - uses: actions/checkout@master
      - uses: tibotiber/hasura-action@master
        with:
          args: migrate apply --database-name default
      - uses: tibotiber/hasura-action@master
        with:
          args: metadata apply
