name: CI

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main]

jobs:
  test-frontend:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm test
      - run: npm run build
        if: github.event_name == 'push'
      - uses: actions/upload-artifact@v2
        if: github.event_name == 'push'
        with:
          name: frontend-build
          path: ./dist
  test-actions:
    defaults:
      run:
        working-directory: ./backend/actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: ./gradlew test
      - run: ./gradlew shadowJar
        if: github.event_name == 'push'
      - uses: actions/upload-artifact@v2
        if: github.event_name == 'push'
        with:
          name: actions-jar
          path: ./build/libs/actions-server-1.0.0-all.jar
