name: CD

on:
  push:
    branches:
      - ps-actions

jobs:
  migrate-hasura:
    runs-on: ubuntu-latest
    env:
      HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
      HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
      HASURA_WORKDIR: ./backend/hasura
    steps:
      - uses: actions/checkout@master
      - uses: tibotiber/hasura-action@master
        with:
          args: migrate apply
      - uses: tibotiber/hasura-action@master
        with:
          args: metadata apply
  vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - working-directory: ./frontend
        run: npm ci && npm run build
      - uses: amondnet/vercel-action@v19
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
